### ISSUE TITLE
improve speeches page

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#445]
![speeches](https://cloud.githubusercontent.com/assets/428820/5532327/bd855daa-8a03-11e4-93c2-67a26024552d.png)

How improve speeches page please

Tnks

**Comment by duncanparkes** [comment]
This is too vague - we're happy to accept specific suggestions.

**Comment by johnfelipe** [comment]
but tell me how integrate that??

**Comment by johnfelipe** [comment]
Hi again
http://concejodemedellin.felipeurrego.com/speeches
is possible create somethin like
http://leveson.sayit.mysociety.org/about
or
http://shakespeare.sayit.mysociety.org/about

**Comment by dracos** [comment]
To create an about page, you put it in about/templates/about/[instance]/index.html. The front page are not latest speeches, they are just static examples, and you create them by making a sayit_mysociety_org/templates/speeches/[instance]/home.html and filling it as with the other examples you can see. These are both just static HTML. (As discussed previously, it would have made more sense for you to have created your own Django project and used SayIt as a Django app within it, then you could have added whatever extra things you wanted in your project on top.)
