### ISSUE TITLE
improve 2 speeches page

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#447]
Ability to organize or move sections?:

![speeches2](https://cloud.githubusercontent.com/assets/428820/5541722/dbcb5042-8aaa-11e4-8cb3-7f89b335e3fb.png)

ACTA 295
ACTA 294

organize or move for:

ACTA 294
ACTA 295

Alphabetically
or
Drag and Drop, like this:
![draganddrop](https://cloud.githubusercontent.com/assets/428820/5541859/b8467ece-8aac-11e4-86ac-86ecd009bc05.png)

Tnks

**Comment by duncanparkes** [comment]
This is issue #16.
