### ISSUE TITLE
update transifex to spanish .../import/akomantoso

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#455]
Import speeches from Akoma Ntoso
Location of Akoma Ntoso data:

What would you like to do with existing top level sections?
  Skip them - keep them exactly as they are
 Replace them - throw away the existing data and use the new
 Duplicate them - just make them again, leaving the old ones in place

Tnks

**Comment by duncanparkes** [comment]
I've pushed new strings to transifex. Sorry I forgot to do this when I added the features.
