### ISSUE TITLE
AN import: bug

### ISSUE THREAD

**Issue by girogiro** [mysociety/sayit#460]
`ImportAkomaNtoso.import_document()` is expected to return imported section at line 118 of `management/import_commands.py` but it actually returns number of imported speakers or None if the section has been skipped.

The bug arises at line 68 of `management/import_commands.py` only with verbose output set on when trying to access id-s in the list of imported sections.

**Comment by dracos** [comment]
A group of overlapping issues here. It looks like it hasn't been returning a section (as `import_commands` appears to expect) for some time; the web interface expects it to return stats, and the returning of `None` was introduced in b4479271ece3b1ed3b241d27d808cb5229b20f77.

It's possible there isn't one "top level" section in an AN file (if there's no docTitle, for example), so what `import_commands.py` is expecting doesn't feel right to me. Would it be okay if it output the stats that the web interface now uses? I've made https://github.com/mysociety/sayit/pull/461 if it is, it would at least remove the bug.

**Comment by girogiro** [comment]
OK for me, I am not using the output, just wanted not to see the bug.

**Comment by girogiro** [comment]
There is one more issue in AN import:

Assume all speeches in the imported file contain startTime and some of them are scene-like types (`scene`, `narrative`, etc.). Only the speech types `speech`, `question`, `answer` respect the startTime, while scene-like speech types do not.

When the speeches are displayed, they are sorted by start_time resulting in all scene-like speeches at the end of the list instead of their original position given by the startTime in the import file.

**Comment by dracos** [comment]
Yes, you're quite right. This will be fixed by adding an order field on import and using it for display #320, rather than trying to go off start time sorting.

**Comment by dracos** [comment]
#461 is merged, so I'm closing this as the other issue is covered by other tickets.
