### ISSUE TITLE
Problem with akoma ntoso import

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#465]
(virtualenv-sayit)notroot@felipeurrego:~/sayit/sayit.mysociety.org$ ./manage.py load_akomantoso --dir=/home/notroot/actas-consejo-medellin/actas-xml --instance=concejodemedellin2013 --commit
	ID #mariadelrosarioescobarpareja in speech has no corresponding TLCPerson entry
	ID #alcaldedemedellinanibalgaviriacorrea in speech has no corresponding TLCPerson entry
	ID #luisbernardovelezmontoya in speech has no corresponding TLCPerson entry

Link Demo: http://concejodemedellin.felipeurrego.com/
Please tell me about that

**Comment by dracos** [comment]
This has already been explained to you at the end of https://github.com/mysociety/sayit.mysociety.org/issues/88#issuecomment-66042689 – “Every ID used by speeches in the document must be specified at the top of the document.” You have a speech using `#mariadelrosarioescobarpareja` as an ID but there is no `TLCPerson` entry, and so on.
