### ISSUE TITLE
Leave a comment in each intervention

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#470]
http://www.nosdeputes.fr/14/seance/2886#inter_323e4096153705169bce61610280663e

**Laisser un commentaire** or leave a comment

That is possible in sayit?

**Comment by dracos** [comment]
SayIt is a Django application. Django has commenting built in as its own app; if you want to use commenting in your use of SayIt, then you should write your own views/templates to allow comments to be left on speeches. I don't think this is something that SayIt itself wants to do, given existing things exist to do this.

**Comment by johnfelipe** [comment]
Please give me  a roadmap or things to expected in sayit, tnks
