### ISSUE TITLE
Sorting bug in Python 3

### ISSUE THREAD

**Issue by girogiro** [mysociety/sayit#472]
In function  `speeches.models._interleave_speeches()` there are two lists joined together and sorted. The first list's sorting key is (datetime, str, int) and the second one's is (datetime, int). The different types on second position results in error: 

``` python
TypeError: unorderable types: int() < str()
```

when sorting in Python 3.

**Comment by dracos** [comment]
If you replace the `""` in the first sorting key with `float('inf')`, that would I think alleviate this issue and have the same effect (as `""` is "greater' than any int in python 2); I have submitted this on the `issues/472-sort-python3` branch if you want to try it out. This is another bug that could be helped by #320, by not trying to be clever, and displaying data in a database-stored sort order.

**Comment by dracos** [comment]
@girogiro Did the commit on that branch fix your problem? I can merge it in if so :)

**Comment by girogiro** [comment]
Yes, it works well. Merge in!
