### ISSUE TITLE
Add jpeg decoder installation required in document

### ISSUE THREAD

**Issue by yhsiang** [mysociety/sayit#486]
Like ubuntu need `$ apt-get install libjpeg-dev` first.
if not install libjpeg-dev, easy_thumbnails cant generate thumbnails.

**Comment by dracos** [comment]
Thanks, I'll add this tomorrow. Note to self: for Debian, it appears to have created a big mess to do with switching from libjpeg to libjpeg-turbo, e.g. jessie lacks libjpeg8 entirely, but libjpeg-dev does appear to exist on all variants, check first.

**Comment by dracos** [comment]
Note added, thanks :)

**Comment by yhsiang** [comment]
:+1:  thx!
