### ISSUE TITLE
Errno::ENOENT on line ["346"] of /usr/lib/ruby/1.9.1/tempfile.rb:

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#487]
CompilerError at /
	Errno::ENOENT on line ["346"] of /usr/lib/ruby/1.9.1/tempfile.rb: No such file or directory - /home/felipe/sayit/sayit.mysociety.org/web/sass/.sass-cache/c847988cb5ca411f41066aba7f61c45548638d0b/project.scssc20150520-1146-52y4gb.lock
	Run with --trace to see the full backtrace
	Request Method:	GET
	Request URL:	http://concejodemedellin.felipeurrego.com/
	Django Version:	1.6.7
	Exception Type:	CompilerError
	Exception Value:	
	Errno::ENOENT on line ["346"] of /usr/lib/ruby/1.9.1/tempfile.rb: No such file or directory - /home/felipe/sayit/sayit.mysociety.org/web/sass/.sass-cache/c847988cb5ca411f41066aba7f61c45548638d0b/project.scssc20150520-1146-52y4gb.lock
	Run with --trace to see the full backtrace
	Exception Location:	/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/pipeline/compilers/__init__.py in execute_command, line 99
	Python Executable:	/home/felipe/sayit/virtualenv-sayit/bin/python
	Python Version:	2.7.6
	Python Path:	
	['/home/felipe/sayit/sayit.mysociety.org',
	 '/usr/bin',
	 '/home/felipe/sayit/virtualenv-sayit/src/django-sayit',
	 '/home/felipe/sayit/virtualenv-sayit/lib/python2.7',
	 '/home/felipe/sayit/virtualenv-sayit/lib/python2.7/plat-x86_64-linux-gnu',
	 '/home/felipe/sayit/virtualenv-sayit/lib/python2.7/lib-tk',
	 '/home/felipe/sayit/virtualenv-sayit/lib/python2.7/lib-old',
	 '/home/felipe/sayit/virtualenv-sayit/lib/python2.7/lib-dynload',
	 '/usr/lib/python2.7',
	 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
	 '/usr/lib/python2.7/lib-tk',
	 '/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages']
	Server time:	Mié, 20 May 2015 15:14:38 -0500

**Comment by dracos** [comment]
That is not an error you should ever get on a production site, because you should never run a production site with `DEBUG` set to True, in which case the static assets would be precompiled. As it what causes it, I don't know, I guess it might be multiple things looking at the page at once and trying to compile simultaneously getting confused? Your site appears to be working fine now, with compiled assets, so I assume you managed to fix this.

**Comment by johnfelipe** [comment]
**THUMBNAIL_DEBUG = True** set to false or delete?
