### ISSUE TITLE
15 seconds for homepage

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#488]
http://concejodemedellin.felipeurrego.com, only homepage open in 15 seconds, other pages and links are tood how fix that?

**Comment by dracos** [comment]
I see that you have made your own additions to your front page. These don't appear to be public anywhere on GitHub, could you push them to your repository on GitHub? If your additions are slow, you will have to investigate and work out what you can do about that.

**Comment by johnfelipe** [comment]
https://github.com/johnfelipe/top9ypalabrascomunes
please help me to fix it

**Comment by dracos** [comment]
The most common speakers is fast; the reason your code is so slow is your word cloud works by iterating over *every* speech in the database one by one, counting up all the words! That's *far* too slow to do within a web request. You should change it so that the data for the word cloud is generated by a separate non-web script that is run regularly, and then your web view reads in and uses that data, with no slowness.

**Comment by johnfelipe** [comment]
I deactivate common words http://concejodemedellin.felipeurrego.com/ and still issue time remains

**Comment by paullenz** [comment]
What happens if you deactivate the word cloud completely?



On 25 May 2015, at 23:29, felipe <notifications@github.com> wrote:

I deactivate common words http://concejodemedellin.felipeurrego.com/ and
still issue time remains

—
Reply to this email directly or view it on GitHub
<https://github.com/mysociety/sayit/issues/488#issuecomment-105307245>.

**Comment by johnfelipe** [comment]
Do you mean delete template?

**Comment by johnfelipe** [comment]
Fix it, but how i can extract in latest speech not use **speeches = Speech.objects.all()**
Tnks

**Comment by dracos** [comment]
"I deactivate common words http://concejodemedellin.felipeurrego.com/ and still issue time remains" - the issue will remain as long as you're looping over all the speeches in a web request, ignoring common words in code is more work for the computer, not less!

I have already told you the only workable solution to generate a word cloud for all speeches – generate the data for the word cloud in a separate script, not within a web request. Run that script regularly. Read in that data in the web request. The web request will then have no work to do and will be faster.

If you only want a word cloud for the latest speech added to the database (not necessarily latest in time), you could use something like `speeches = Speech.objects.order_by('-id')[0]` (or [0:10] for the latest 10 speeches). The Django documentation on query sets explains all the options for querying the database.

**Comment by johnfelipe** [comment]
Please share django docu link

**Comment by dracos** [comment]
https://docs.djangoproject.com/en/1.7/ref/models/querysets/

**Comment by johnfelipe** [comment]
Dont work for me:

https://github.com/johnfelipe/top9ypalabrascomunes/blob/master/speeches/templatetags/speech_extension.py#L58

	source virtualenv-sayit/bin/activate
	cd sayit.mysociety.org/
	python manage.py collectstatic
	deactivate
	sudo /etc/init.d/gunicorn restart

and all in speech_extension.py gone...

**Comment by dracos** [comment]
I'm sorry to hear it doesn't work. You will have to do some debugging to work out why, this is not SayIt code, this is code you have written. That certainly does return the same sort of dataset here, just only 10 speeches, e.g.:

```python
>>> Speech.objects.all()
[<Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, '...(remaining elements truncated)...']
>>> Speech.objects.order_by('-id')[0:10]
[<Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>, <Speech>]
```

**Comment by johnfelipe** [comment]
this: speeches = Speech.objects.all(), work

	#speeches = Speech.objects.order_by('-id')[0]
	#speeches = Speech.objects.order_by('-id')[0:10]

Dont work.
Please share me multiple options for try
Tnks

**Comment by dracos** [comment]
"Don't work" is of no help to anyone. In what way doesn't it work? A template tag will eat up any errors, so you need to replicate the same code at the command line in order to see what error is happening. It could be as simple as an unfixed indentation error, I can't work it you for you. I would start a shell with `python manage.py shell` and try things out to see what works and what doesn't, I can't suggest other things to try when the things I suggest work okay for me.

**Comment by johnfelipe** [comment]
(virtualenv-sayit)felipe@actasfelipe:~/sayit/sayit.mysociety.org$ python manage.py shell
	Python 2.7.6 (default, Mar 22 2014, 22:59:56)
	[GCC 4.8.2] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	(InteractiveConsole)
	>>> Speech.objects.order_by('-id')[0:10]
	Traceback (most recent call last):
	  File "<console>", line 1, in <module>
	NameError: name 'Speech' is not defined
	>>>

**Comment by dracos** [comment]
I am not here to teach you how to use the Django console. If you wish to develop things that use Django, read the manual, and learn how to use it. https://docs.djangoproject.com/en/1.7/

**Comment by dracos** [comment]
It is a python prompt. You need to import the models you wish to use, just like in the python scripts.

**Comment by dracos** [comment]
```python
$ python manage.py shell
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from speeches.models import Speech
>>> Speech.objects.order_by('-id')[0:10]
[<Speech: Speech>, <Speech: Speech>, <Speech: Speech>, <Speech: Speech>, <Speech: Speech>, <Speech: Speech>, <Speech: Speech, <Speech: Speech>, <Speech>, <Speech>]
```

**Comment by johnfelipe** [comment]
[<Speech: Speech by unknown at 2015-04-12 (with text)>, <Speech: [Bad Unicode data]>, <Speech: Speech by Bernardo Alejandro Guerra Hoyos at 2015-04-12 (with text)>, <Speech: [Bad Unicode data]>, <Speech: [Bad Unicode data]>, <Speech: Speech by Bernardo Alejandro Guerra Hoyos at 2015-04-12 (with text)>, <Speech: [Bad Unicode data]>, <Speech: Speech by Fabio Humberto Rivera Rivera at 2015-04-12 (with text)>, <Speech: Speech by Carlos Mario Uribe Zapata at 2015-04-12 (with text)>, <Speech: [Bad Unicode data]>]

**Comment by dracos** [comment]
So it works from the command line, returning 10 speeches, as I said. So it should work in the template tag, just the same. If it does not, then you will have to investigate further what is happening, with debug statements, debugging, however you want to do it.
