### ISSUE TITLE
The 3-level hierarchy

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#490]
<debatebody>
	  <debatesection>
		<heading>2012</heading>
		<debatesection>
		  <heading>7</heading>
		  <debatesection>
			<heading>ACTA No. 01, 25.7.2012</heading>
is better for user is there is only 1-2 debates per day. It saves one click to read the actual debate.

This is xml generated

https://github.com/johnfelipe/hierarchyactasconcejodemedellin

But upload with akomantoso command:

**./manage.py load_akomantoso --file=/home/notroot/actas-consejo-medellin/actas-xml/24152.xml --instance=concejodemedellin --commit**

![1](https://cloud.githubusercontent.com/assets/428820/7972195/2637bf0a-0a10-11e5-97ba-ae61acc70980.png)

![2](https://cloud.githubusercontent.com/assets/428820/7972203/34c817f4-0a10-11e5-9b63-3d7b3ed5f0f8.png)

Why?
Please tell me how fix it?

**Comment by dracos** [comment]
It sounds like you might want to investigate the `--merge-existing` argument to the import command, which should merge all your "2013" sections together; by default an import imports everything in the file as new. So I think that should hopefully fix the issue you raise here.

A better solution is for your XML not to have the year/month debateSections, but to instead put a date in the preface, and you write some small custom date-based views to display them however you want; this would be better than a hierarchical based approach. #103 is our ticket to add some default views to SayIt itself, but I'm afraid we have not as yet had the time to create them.

**Comment by johnfelipe** [comment]
Same result 

./manage.py load_akomantoso --dir=/home/notroot/actas-consejo-medellin/actas-xml --instance=concejodemedellin --commit --merge-existing

	Importing 2013
	Importing 07
	Importing ACTA 299

	Importing 2013
	Importing 07
	Importing ACTA 300

	Importing 2013
	Importing 07
	Importing ACTA 304

	Importing 2013
	Importing 07
	Importing ACTA 305

	Importing 2013
	Importing 08
	Importing ACTA 317

	Importing 2013
	Importing 10
	Importing ACTA 329

	Importing 2013
	Importing 10
	Importing ACTA 332

	Importing 2013
	Importing 10
	Importing ACTA 342

	Importing 2013
	Importing 10
	Importing ACTA 344

	Importing 2013
	Importing 10
	Importing ACTA 345

	Importing 2013
	Importing 11
	Importing ACTA 380

	Importing 2013
	Importing 12
	Importing ACTA 381

	Importing 2013
	Importing 12
	Importing ACTA 384

	Importing 2013
	Importing 12
	Importing ACTA 383

	Importing 2013
	Importing 12
	Importing ACTA 384

	Importing 2013
	Importing 12
	Importing ACTA 385

	Importing 2013
	Importing 12
	Importing ACTA 386

	Importing 2013
	Importing 12
	Importing ACTA 387

	Importing 2013
	Importing 12
	Importing ACTA 389

	Importing 2013
	Importing 12
	Importing ACTA 390

	Importing 2013
	Importing 12
	Importing ACTA 391

	Importing 2013
	Importing 12
	Importing ACTA 392

	Importing 2013
	Importing 12
	Importing ACTA 393

![1](https://cloud.githubusercontent.com/assets/428820/7972195/2637bf0a-0a10-11e5-97ba-ae61acc70980.png)

![2](https://cloud.githubusercontent.com/assets/428820/7972203/34c817f4-0a10-11e5-9b63-3d7b3ed5f0f8.png)

What missing?

**Comment by dracos** [comment]
The code in the link you provide does not match the code you quote in the issue above.

**Comment by johnfelipe** [comment]
this: 

./manage.py load_akomantoso --dir=/home/notroot/actas-consejo-medellin/actas-xml --instance=concejodemedellin --commit --merge-existing

or this:

https://github.com/johnfelipe/hierarchyactasconcejodemedellin

**Comment by johnfelipe** [comment]
<debatebody>
	  <debatesection>
		<heading>2012</heading>
		<debatesection>
		  <heading>7</heading>
		  <debatesection>
			<heading>ACTA No. 01, 25.7.2012</heading>

with this

https://github.com/johnfelipe/hierarchyactasconcejodemedellin

		<debateBody>
			<debateSection>
				<debateSection>
					<debateSection>
						<heading>ACTA 354
						</heading>
					</debateSection>
					<heading>10</heading>
				</debateSection>
				<heading>2013</heading>
			</debateSection>
		</debateBody>

Latest is bad?

**Comment by dracos** [comment]
Oh, you have written your XML upside down for some reason, with the headings after the content, rather than before it. Sorry, I didn't spot that. Theoretically, that should still work okay, I guess, I'm not sure.

**Comment by dracos** [comment]
The top level section sets its start date to the start date given in each XML file, so they are all different from the importer's point of view.

**Comment by dracos** [comment]
If you have put a hierarchy in the debateSection, then to import correctly I think you will want to remove the docDate from the preface. But as I say above, I don't really recommend this as a nice way of doing it.

**Comment by johnfelipe** [comment]
Please share me xml code example with my need

**Comment by dracos** [comment]
I have given you all the help I can. As I said, try removing the &lt;docDate&gt; from the preface of all your XML, as that makes all your "2013"s different.

**Comment by johnfelipe** [comment]
Solved removing docDate, tnks, close this issue
