### ISSUE TITLE
Questions in akomantoso

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#493]
<questions>
		<narrative>ADITIVO A LA PROPOSICIÓN No. 35/12</narrative>
		<narrative>Al Señor Alcalde Mayor de Bogotá, Dr. Gustavo Petro; al Doctor Diego Bravo, Gerente Empresa de Acueducto y Alcantarillado; y al Doctor Ricardo Agudelo, Gerente de Aguas Bogotá</narrative>
		<question>1. Describa el modelo operacional, logístico y financiero asumido por la gerencia de aguas capital para la presentación del servicio de aseo a partir del 18 de diciembre de 2012.</question>
		<question>2. Relacione la estructura de costos recolección, barrido y transporte, así como los gastos de administración. Anexe un cuadro comparativo de costos en relación con los costos para la prestación del servicio por parte de los operadores privados.</question>
		<question>3. ¿Cómo se garantizará la rebaja en las tarifas de aseo con el nuevo esquema de aseo en Bogotá? Sírvase indicar qué estratos serán beneficiados y la fecha de aplicación de la misma.</question>
		<question>4. De acuerdo con el nuevo esquema de aseo ¿Qué estudios o proyecciones se han realizado para evaluar las rebajas en la tarifa del aseo en Bogotá? Sírvase anexar los soportes correspondientes.</question>
		<question>5. ¿Qué sobrecostos se han generado con la implementación de nuevo esquema de aseo en Bogotá? Sírvase informar que implicaciones tiene en la tarifa.</question>
		<question>6. Señale si aguas de Bogotá ha sido objeto de demandas por incumplimiento de contratos, demandas de responsabilidad civil, y demandas contractuales y extracontractuales.</question>
		<question>7. ¿Cuál fue el procedimiento y criterio de selección por parte de aguas de Bogotá para la adjudicación a la Unión Temporal Aseo Districapital para el alquiler de la flota compactadoras?. Anexe acta de evaluación de propuestas y le experiencia de la firma en este tipo de contratos.</question>
		<question>8. Anexe los informes de las visitas realizadas por lo funcionarios que viajaron a los estados unidos para verificar las condiciones técnicas y operacionales de los vehículos que serían objeto del alquiler por parte de aguas capital.</question>
		<narrative>Al Señor Alcalde Mayor de Bogotá, Gustavo Petro; a la Doctora Nelly Mogollón, Directora de la Unidad Administrativa Especial de Servicios Públicos de Bogotá</narrative>
		<question>1. ¿Qué acciones se han emprendido por parte de la administración distrital para verificar si los operadores cumplieron las condiciones del contrato antes del día 18 Diciembre, fecha de terminación de los mismos?</question>
		<question>2. Señale la condiciones económicas y jurídicas pactadas por parte de la Unidad administrativa de servicios púbicos UESPA con los operadores Lime, Ciudad Limpia, Atesa y Aseo Capital para el restablecimiento de la prestación de servicio. Y a su vez indique el impacto sobre la tarifas de esta decisión.</question>
		<question>3. ¿Cuántas organizaciones de recicladores y recicladores están vinculados al nuevo esquema de prestación del servicio de aseo? , señale a su vez el esquema de remuneración financieramente estipulado para dar cumplimiento al auto 215 de 2011.</question>
		<question>4. ¿Cómo se garantizará la rebaja en las tarifas de aseo con el nuevo esquema de aseo en Bogotá? Sírvase indicar qué estratos serán beneficiados y la fecha de aplicación de la misma.</question>
		<question>5. De acuerdo con el nuevo esquema de aseo ¿Qué estudios o proyecciones se han realizado para evaluar las rebajas en la tarifa del aseo en Bogotá? Sírvase anexar los soportes correspondientes.</question>
		<question>6. ¿Qué sobrecostos se han generado con la implementación de nuevo esquema de aseo en Bogotá? Sírvase informar que implicaciones tiene en la tarifa.</question>
		<narrative>A la Superintendencia de Servicios Públicos Domiciliarios; y a la Comisión de Regulación de Agua Potable y Saneamiento Básico</narrative>
		<question>1. Informe sobre quejas formales que haya recibido sobre la prestación del servicio de aseo en la ciudad de Bogotá a partir del 28 de diciembre de 2012</question>
		<question>2. Describe las actividades que haya adelantado la Superintendencia para la verificación del cumplimiento de la prestación del Servicio de aseo en la ciudad de Bogotá, a partir del 28 de Diciembre de 2102. ¿Qué medidas ha tomado la superintendencia para verificar que en Bogotá se hayan reducido las tarifas en la prestación del servicio de aseo conforme a las públicas afirmaciones del Alcalde Petro. ¿Cuáles son las posibilidades de reducir la tarifa de aseo en la ciudad de Bogotá a partir de un cambio en el esquema operacional? I </question>
	</questions>

why **Untitled**

![questions](https://cloud.githubusercontent.com/assets/428820/8079155/632351f0-0f28-11e5-99ba-46210f7de9c4.png)

In each questions **an unknown speaker**

![oradordesconocido](https://cloud.githubusercontent.com/assets/428820/8079316/48d6e5f4-0f29-11e5-983e-7aea5094e6ea.png)

How fix that?

**Comment by dracos** [comment]
The documentation at http://sayit.mysociety.org/about/developers is clear. `questions` needs a `heading` element if you wish to give it a heading, and `question` is the same as `speech`, and must provide a `by` attribute if you wish it to have a speaker. Please follow the documentation.
