### ISSUE TITLE
How top 30 for instance in sayit

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#496]
http://senado.felipeurrego.com

http://concejodemedellin.felipeurrego.com

It same, how put top 30 for each instance not for all?
Tnks

**Comment by dracos** [comment]
Where is the code that generates that output? Hard to help without you having put it on github somewhere or letting us know where it is.

I imagine the code needs to filter by instance in its query somewhere in its process, so shouldn't be too hard.

**Comment by johnfelipe** [comment]
Sorry, this is
https://github.com/johnfelipe/top9ypalabrascomunes/tree/master/speeches/templates/speeches

**Comment by dracos** [comment]
You will need to alter the `get_top_speakers` template tag to take the instance as an argument, so in the _top_speakers.html template you will want `{% get_top_speakers request.instance.label as top_speakers %}`, and `get_top_speakers` has two arguments, instance and count, and then you would change `Speech.objects.values('speaker')` to something like `Speech.objects.for_instance(instance).values('speaker')` to only include speeches in the right instance.

**Comment by johnfelipe** [comment]
I change top speaker to:

	{% load speech_i18n %}
	{% load speech_extension %}
	{% load thumbnail %}
	{% load staticfiles %}

	<br><br>
	<h3>{% trans 'Top 30 Oradores' %}</h3>
	{% get_top_speakers request.instance.label as top_speakers %}

	<div class="row top-speakers">


		{% for speaker in top_speakers %}
		<a href="{{ speaker.get_absolute_url }}">
			<div class="speaker">
				<img src="{% if speaker.image_cache %}{{ speaker.image_cache|thumbnail_url:'speaker-thumb' }}{% elif speaker.image %}{{ speaker.image }}{% else %}{% static "speeches/i/a.png" %}{% endif %}"
							 style="border-color: #{{ speaker.colour }}; background-color: #{{ speaker.colour }};" alt="" class="speaker-card__portrait speaker-portrait round-image speaker-portrait--small">
				{{ speaker}}<br>
				<small>{{ speaker.count }} {% if speaker.count == 1 %} speech {% else %} speeches {% endif %}</small>
			</div>
		</a>
		{% endfor %}

	</div>

and

get_top_speakers in speech_extension.py to:

	def get_top_speakers(count=30):
		from speeches.models import Speech, Speaker
		from django.db.models import Count

		top_speakers_list = Speech.objects.for_instance(instance).values('speaker').annotate(count=Count('speaker')).order_by('speaker').order_by(
			'-count')[0:count]
		top_speakers = []
		for speaker in top_speakers_list:
			the_speaker = Speaker.objects.get(pk=speaker['speaker'])
			# setattr(the_speaker, 'count', speaker['count])
			the_speaker.count = speaker['count']
			top_speakers.append(the_speaker)
		return top_speakers

i do this:

	python manage.py collectstatic
	sudo /etc/init.d/nginx restart
	sudo /etc/init.d/gunicorn restart

and:

![internarservererror](https://cloud.githubusercontent.com/assets/428820/8262561/c0985872-1698-11e5-9517-79ee1221523e.png)

**Comment by dracos** [comment]
Most obviously, `def get_top_speakers(count=30)` does not have two arguments, as I said, it should be `def get_top_speakers(instance, count=30)`. There may be other issues, I am not debugging your code for you, this is not a SayIt issue, this is your own code. Look at your error logs, find out what the error is, work out the mistake or mistakes.
