### ISSUE TITLE
Blank page after git pull

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#498]
![nosalenada](https://cloud.githubusercontent.com/assets/428820/8294732/fe6ade96-1903-11e5-8a17-97c78062168d.png)

Select **ACTA No. 24 / 04-12-2012**

![nosalenada2](https://cloud.githubusercontent.com/assets/428820/8294736/08906a80-1904-11e5-9d6b-18382d873c64.png)

And all new hansard imported show blank page and no infor only space
How fix that?

**Comment by johnfelipe** [comment]
fix temporarly with
´git reset --hard 35ee831d6047e7ef5b00eddce8bbf94a8723f9fc´
Then how fix with update code?

**Comment by dracos** [comment]
This should be okay with the latest commit.
