### ISSUE TITLE
Use regular arrows in back/forward buttons

### ISSUE THREAD

**Issue by wfdd** [mysociety/sayit#509]
See [guillemet](https://en.wikipedia.org/wiki/Guillemet) and [[1]](http://cypriot-mps-questions.sayit.mysociety.org/speech/655011). (Yes, the quote marks are likely superfluous here, but it might be worth fixing anyway.)

**Comment by dracos** [comment]
Thanks; fixed in 3a6298ed9cdaf419313fb12d2d95a59aa9ee1c63
