### ISSUE TITLE
performance grade

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#519]
https://tools.pingdom.com/#!/cvYqJR/http://actas.concejointeractivorionegro.co:2017/

I need up that grade, is possible?

**Comment by dracos** [comment]
Yes, you need to do what it says - serve your static content with a longer expiry time and with a Vary: Accept-Encoding header. This is not a Sayit issue, it looks like you are using nginx as your web server so you can set such headers things there, as explained in the various documentation linked from the page you quote.
