### ISSUE TITLE
[Support] Is tasypie installed on sayit.mysociety.org instances

### ISSUE THREAD

**Issue by patcon** [mysociety/sayit#524]
Just trying to track down the API endpoint to mass-delete a bunch of sections, and can't seem to dig them up. Does this exist? Thanks!

**Comment by dracos** [comment]
Tastypie is installed on sayit.mysociety.org, yes, e.g. http://leveson.sayit.mysociety.org/api/v0.1/?format=json but I'm afraid it is read only. You would currently have to post to the HTML delete endpoint with a logged in cookie, for example.
