### ISSUE TITLE
Wrong pronounciaton

### ISSUE THREAD

**Issue by derrapf** [mysociety/sayit#527]
I switched Sayit to AWS Polly Marlene and have issues when it tries to say numbers like temperatures and humidities.
Example:

- "es ist 1.2 °C" will be pronounced as "Es ist erste zwei Grad Celsius" 
That is simply wrong and nobody understands that. I should be "Es ist eins komma 2 Grad Celsius" or at least "Es ist eins punkt zwei Grad Celsius"
- "es ist 3.14 °C" will be pronounced as "es ist dritte vierzehn Grad Celsius", which is wrong as well.
- It is getting worse when it tries to say "es ist 3.141 °C". This will result in "Es ist dreitausend einhundert einundvierzig Grad Celsius", which is completely BS.
- It is not getting better with more digits: "es ist 3.1415 °C" results in "es ist dritter eintausend vierhundert fünfzehn Grad Celsius" 

That is completely unusable.

Ralf

**Comment by johnfelipe** [comment]
@derrapf can u share me or buy me your script for swtiched Sayit to AWS Polly Marlene
Stay alert

**Comment by derrapf** [comment]
Hi
>@ <https://github.com/derrapf> derrapf can u share me or buy me your script for swtiched Sayit to AWS Polly Marlene


I don’t understand. What script are you talking about?
To test my issue you just enter text like „say 3.1.45 °C“ into the sayit.0.tts.text variable
Regards Ralf

**Comment by johnfelipe** [comment]
I haven't tts in sayit I want to test in Spanish, I have sayit app
installed in Ubuntu, pls help me

**Comment by derrapf** [comment]
Oh. Sorry. I just recognized that i placed that issue in the wrong place. I use Iobroker and sayit. So I guess i am in the wrong repository here. I will close that issue here.

**Comment by derrapf** [comment]
Closed and moved to ioBroker/ioBroker.sayit

**Comment by johnfelipe** [comment]
Have u a demo link with issue?

**Comment by derrapf** [comment]
I placed it here now:
https://github.com/ioBroker/ioBroker.sayit/issues/20
