### ISSUE TITLE
is not searching

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#529]
Hi again, pls tell me what need to review because is not working search

http://comisionsextacamara.jhonfelipeurregomejia.com/search/?q=Hacienda

im using ubuntu 14 and install elasticsearch with this steps:

	wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

	sudo apt-get install apt-transport-https

	echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list

	sudo apt-get update && sudo apt-get install elasticsearch

Stay alert

**Comment by johnfelipe** [comment]
felipe@ACTASINTELIGENTES:~$ curl -XGET 'localhost:9200/?pretty'
	{
	  "name" : "4M8ggK4",
	  "cluster_name" : "elasticsearch",
	  "cluster_uuid" : "GYfLdu4JRgWL1o7FmActQQ",
	  "version" : {
		"number" : "5.4.0",
		"build_hash" : "780f8c4",
		"build_date" : "2017-04-28T17:43:27.229Z",
		"build_snapshot" : false,
		"lucene_version" : "6.5.0"
	  },
	  "tagline" : "You Know, for Search"
	}

**Comment by johnfelipe** [comment]
is not working with 5.4.0 only until 2.4.5, is possible update this?

**Comment by dracos** [comment]
Did you keep the version of the elasticsearch python module in sync with whichever version of elasticsearch you have installed? This sounds to me exactly the same issue you had before: https://github.com/mysociety/sayit.mysociety.org/issues/97#issuecomment-214815417
`You are running a version of the elasticsearch PyPI module that is incompatible with the version of elasticsearch you are running.` – if you are running elasticsearch 5.4.0, then you need install version 5.4.0 of the elasticsearch module, as it tells you here: https://pypi.python.org/pypi/elasticsearch/5.4.0

**Comment by johnfelipe** [comment]
then i need to do this:

Inside a virtualenv, and "pip install elasticsearch==5.0.0" to install that version??

**Comment by dracos** [comment]
If you are running elasticsearch 5.0.0, yes. If you're running 5.4.0 as you said you were above, then you should install 5.4.0...

**Comment by johnfelipe** [comment]
Hi bro, finally i can test, this is my steps

	felipe@devpythonodejs:~/sayit/sayit.mysociety.org$ cd
	felipe@devpythonodejs:~$ cd sayit/
	felipe@devpythonodejs:~/sayit$ source virtualenv-sayit/bin/activate
	(virtualenv-sayit) felipe@devpythonodejs:~/sayit$ cd sayit.mysociety.org/
	(virtualenv-sayit) felipe@devpythonodejs:~/sayit/sayit.mysociety.org$ pip freezeasn1crypto==0.22.0
	audioread==2.1.5
	beautifulsoup4==4.6.0
	bleach==2.0.0
	certifi==2017.7.27.1
	cffi==1.10.0
	chardet==3.0.4
	cryptography==2.0.3
	Django==1.8.18
	django-allauth==0.25.2
	django-apptemplates==1.0
	django-bleach==0.3.0
	django-haystack==2.5.1
	django-model-utils==3.0.0
	django-pipeline==1.6.13
	-e git+https://github.com/mysociety/sayit@a3f1e1923dc831046812c2266702d7e0ba7d4a6b#egg=django_sayit
	django-subdomain-instances==2.0
	django-tastypie==0.14.0
	easy-thumbnails==2.4.1
	**elasticsearch==5.4.0**
	enum34==1.1.6
	futures==3.1.1
	gunicorn==17.5
	html5lib==0.999999999
	idna==2.6
	ipaddress==1.0.18
	lxml==3.8.0
	mysociety-django-pipeline-compass-rubygem==0.1.8.1
	mysociety-django-popolo==0.0.8
	mysociety-Django-Select2==4.3.2.1
	mysociety-django-sluggable==0.2.7
	ndg-httpsclient==0.4.2
	oauthlib==2.0.2
	olefile==0.44
	Pillow==4.2.1
	psycopg2==2.5.5
	pyasn1==0.3.2
	pycparser==2.18
	pyOpenSSL==17.2.0
	python-dateutil==2.6.1
	python-memcached==1.58
	python-mimeparse==1.6.0
	python-openid==2.2.5
	pytz==2017.2
	PyYAML==3.12
	requests==2.18.4
	requests-cache==0.4.13
	requests-oauthlib==0.8.0
	six==1.10.0
	unicode-slugify==0.1.1
	urllib3==1.22
	webencodings==0.5.1

next i do this

	(virtualenv-sayit) felipe@devpythonodejs:~/sayit/sayit.mysociety.org$ sudo /etc/init.d/elasticsearch status
	 * elasticsearch is running
	(virtualenv-sayit) felipe@devpythonodejs:~/sayit/sayit.mysociety.org$ curl -XGET 'localhost:9200/?pretty'
	{
	  "name" : "jtw_NEd",
	  "cluster_name" : "elasticsearch",
	  "cluster_uuid" : "1HFwsLztQSq-lmoXQtV-KQ",
	  "version" : {
		"number" : "5.5.2",
		"build_hash" : "b2f0c09",
		"build_date" : "2017-08-14T12:33:14.154Z",
		"build_snapshot" : false,
		"lucene_version" : "6.6.0"
	  },
	  "tagline" : "You Know, for Search"
	}

but when put http://comisionsextacamara.jhonfelipeurregomejia.com/search/?q=colombia

![pantallazo-0305](https://user-images.githubusercontent.com/428820/30345311-399f3d1c-97ca-11e7-8955-6422753cbe70.png)

**Comment by johnfelipe** [comment]
felipe@devpythonodejs:~$ aptitude show elasticsearch
	Package: elasticsearch
	State: installed
	Automatically installed: no
	Version: 5.5.2
	Priority: optional
	Section: web
	Maintainer: Elasticsearch Team <info@elastic.co>
	Architecture: all
	Uncompressed Size: 37.3 M
	Depends: libc6, adduser, bash
	Description: Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
	 Elasticsearch subproject :distribution:deb
	Homepage: https://www.elastic.co/

How solve this?

**Comment by LuisAlejandro** [comment]
@dracos That is not the case here.

Sayit uses Haystack as a search engine. Haystack only supports versions 1.0+ and 2.0+ as its stated on the docs:

https://github.com/django-haystack/django-haystack/blob/master/docs/installing_search_engines.rst#elasticsearch

Support for 5.0+ version is still pending on this pull request:

https://github.com/django-haystack/django-haystack/pull/1461

So, the solution is to install haystack from this pull, or downgrade to ES 2.0

**Comment by dracos** [comment]
@LuisAlejandro Thanks for the information. I will update the install docs to say you must install ES0.x, 1.x, or 2.x.
